name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Add a test to ping the Replit server
      - name: Test connection to Replit
        run: |
          ping -c 4 finalprojectbe.replit.app

      # Run the SSH command with more verbose output
      - name: Deploy to Replit
        run: |
          echo "$REPLIT_SSH_KEY" | tr -d '\r' > ~/id_rsa
          chmod 600 ~/id_rsa
          ssh -vvv -o LogLevel=DEBUG3 -i ~/id_rsa -p 22 -o StrictHostKeyChecking=no repl@finalprojectbe.replit.app "cd /home/runner/finalprojectbe && git pull && npm install && pm2 restart all"

        env:
          REPLIT_SSH_KEY: ${{ secrets.REPLIT_SSH_KEY }}
