name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | bash
        export PATH=$PATH:/root/.railway/bin

    - name: Authenticate with Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway login --token $RAILWAY_TOKEN

    - name: Deploy to Railway
      run: railway up
